# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: .NET Version
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      & dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
      & dotnet workload install android maui wasm-tools ios --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json

- task: DotNetCoreCLI@2
  name: "Build"
  inputs:
    command: 'build'
    projects: '**/KlidecekIS.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  name: "Test"
  inputs:
    command: 'test'
    projects: '**/KlidecekIS.sln'
    arguments: '--configuration $(buildConfiguration)'